# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e52d40f3d63df4b982740600335fd9336992e471020b15b6978e9a8f8d01b5e7c5a59e59a5baa458fc0b78ff792574d92e16405fea313dc1f02aa77582695099

test:
  secret_key_base: 4953b908e21df586d20a9515b98a85e77826eb438abae2e0677a1228f72037a150edebc1bd341acb4c8efa4b038bc4fbd28aa8eee5c0a0ff196c55ceca87415f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
